apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsales-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: carsales-api
  template:
    metadata:
      labels:
        app: carsales-api
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 1000
      containers:
        - name: carsales-api
          image: larissay/subiv-carsales:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: carsales-config
            - secretRef:
                name: carsales-secrets
          volumeMounts:
            - name: cars-main-data
              mountPath: /data
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 5

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 12

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
      volumes:
        - name: cars-main-data
          persistentVolumeClaim:
            claimName: cars-main-pvc
