apiVersion: v1
kind: PersistentVolume
metadata:
  name: cars-main-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /tmp/subiv-carsales-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cars-main-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
